# Generated by Django 4.2.7 on 2023-12-13 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='auctionlisting',
            name='current_bid',
        ),
        migrations.RemoveField(
            model_name='auctionlisting',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
