# Generated by Django 4.2.7 on 2023-12-13 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_remove_auctionlisting_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='current_bid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
