# Generated by Django 4.2.7 on 2023-12-13 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auctionlisting_current_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('inactive', 'Inactive')], default='open', max_length=10),
        ),
    ]
