# Generated by Django 4.2.7 on 2023-12-13 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auctionlisting_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2022-01-01T00:00:00Z'),
            preserve_default=False,
        ),
    ]
